export const mockMeal = [
  {
    title: "12.08.22",
    data: [
      {
        id: "1",
        name: "Chicken and Rice",
        description: "Chicken and Rice with vegetables",
        date: "2021-01-01",
        time: "12:00",
        isInDiet: true,
      },
      {
        id: "2",
        name: "Chicken and Rice",
        description: "Chicken and Rice with vegetables",
        date: "2021-01-01",
        time: "12:00",
        isInDiet: false,
      },
      {
        id: "3",
        name: "Chicken and Rice",
        description: "Chicken and Rice with vegetables",
        date: "2021-01-01",
        time: "12:00",
        isInDiet: true,
      },
      {
        id: "4",
        name: "Chicken and Rice",
        description: "Chicken and Rice with vegetables",
        date: "2021-01-01",
        time: "12:00",
        isInDiet: true,
      },
    ],
  },
  {
    title: "11.08.22",
    data: [
      {
        id: "5",
        name: "Chicken and Rice",
        description: "Chicken and Rice with vegetables",
        date: "2021-01-01",
        time: "12:00",
        isInDiet: true,
      },
      {
        id: "6",
        name: "Chicken and Rice",
        description: "Chicken and Rice with vegetables",
        date: "2021-01-01",
        time: "12:00",
        isInDiet: true,
      },
      {
        id: "7",
        name: "Chicken and Rice",
        description: "Chicken and Rice with vegetables",
        date: "2021-01-01",
        time: "12:00",
        isInDiet: true,
      },
      {
        id: "8",
        name: "Chicken and Rice",
        description: "Chicken and Rice with vegetables",
        date: "2021-01-01",
        time: "12:00",
        isInDiet: true,
      },
    ],
  },
  {
    title: "10.08.22",
    data: [
      {
        id: "9",
        name: "Chicken and Rice",
        description: "Chicken and Rice with vegetables",
        date: "2021-01-01",
        time: "12:00",
        isInDiet: true,
      },
      {
        id: "10",
        name: "Chicken and Rice",
        description: "Chicken and Rice with vegetables",
        date: "2021-01-01",
        time: "12:00",
        isInDiet: true,
      },
      {
        id: "11",
        name: "Chicken and Rice",
        description: "Chicken and Rice with vegetables",
        date: "2021-01-01",
        time: "12:00",
        isInDiet: true,
      },
      {
        id: "12",
        name: "Chicken and Rice",
        description: "Chicken and Rice with vegetables",
        date: "2021-01-01",
        time: "12:00",
        isInDiet: true,
      },
    ],
  },
];
