export const mockMeal = [
  {
    title: "12.08.22",
    data: [
      {
        id: "1",
        name: "Chicken and Rice",
        description: "Chicken and Rice with vegetables",
        date: new Date(),
        time: new Date().getTime(),
        isInDiet: true,
      },
      {
        id: "2",
        name: "Grilled Chicken",
        description: "Chicken and Rice with vegetables",
        date: new Date(),
        time: new Date().getTime(),
        isInDiet: false,
      },
      {
        id: "3",
        name: "Roasted Chicken",
        description: "Chicken and Rice with vegetables",
        date: new Date(),
        time: new Date().getTime(),
        isInDiet: true,
      },
      {
        id: "4",
        name: "Baked Chicken",
        description: "Chicken and Rice with vegetables",
        date: new Date(),
        time: new Date().getTime(),
        isInDiet: true,
      },
    ],
  },
  {
    title: "11.08.22",
    data: [
      {
        id: "5",
        name: "Boiled Chicken",
        description: "Chicken and Rice with vegetables",
        date: new Date(),
        time: new Date().getTime(),
        isInDiet: true,
      },
      {
        id: "6",
        name: "Chicken Fried Rice",
        description: "Chicken and Rice with vegetables",
        date: new Date(),
        time: new Date().getTime(),
        isInDiet: true,
      },
      {
        id: "7",
        name: "Mashed Chicken",
        description: "Chicken and Rice with vegetables",
        date: new Date(),
        time: new Date().getTime(),
        isInDiet: true,
      },
      {
        id: "8",
        name: "Beef and Rice",
        description: "Chicken and Rice with vegetables",
        date: new Date(),
        time: new Date().getTime(),
        isInDiet: true,
      },
    ],
  },
  {
    title: "10.08.22",
    data: [
      {
        id: "9",
        name: "Sliced Chicken",
        description: "Chicken and Rice with vegetables",
        date: new Date(),
        time: new Date().getTime(),
        isInDiet: true,
      },
      {
        id: "10",
        name: "Gourmet Chicken",
        description: "Chicken and Rice with vegetables",
        date: new Date(),
        time: new Date().getTime(),
        isInDiet: true,
      },
      {
        id: "11",
        name: "Spicy Chicken",
        description: "Chicken and Rice with vegetables",
        date: new Date(),
        time: new Date().getTime(),
        isInDiet: true,
      },
      {
        id: "12",
        name: "Slim Chicken",
        description: "Chicken and Rice with vegetables",
        date: new Date(),
        time: new Date().getTime(),
        isInDiet: true,
      },
    ],
  },
];
